"""Python bindings for the mathlib C++ library, generated by mirror_bridge."""

import os
import sys

_dir = os.path.dirname(os.path.abspath(__file__))
if _dir not in sys.path:
    sys.path.insert(0, _dir)

try:
    from mathlib import *
except ImportError:
    raise ImportError(
        "mathlib.so not found. Build it first:\n"
        "  mirror_bridge generate src/ --module mathlib --lang python\n"
        "  cp build/mathlib.so my_mathlib/"
    )
