#pragma once

// ============================================================================
// Mirror Bridge - Python Type Stub (.pyi) Generation
// ============================================================================
//
// Generates Python type stubs for IDE autocompletion and type checking.
// Metadata is collected during bind_class() and can be exported to .pyi files.
//
// Usage:
//   MIRROR_BRIDGE_MODULE(mymodule,
//       mirror_bridge::bind_class<MyClass>(m, "MyClass");
//       mirror_bridge::bind_class<Other>(m, "Other");
//
//       // Generate stubs
//       mirror_bridge::stubgen::write_stubs("mymodule.pyi");
//   )
//
// ============================================================================

#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <fstream>
#include <typeinfo>
#include <cxxabi.h>

namespace mirror_bridge {
namespace stubgen {

// ============================================================================
// Stub Metadata Storage
// ============================================================================

struct ParameterInfo {
    std::string name;
    std::string type_hint;
};

struct MethodInfo {
    std::string name;
    std::vector<ParameterInfo> parameters;
    std::string return_type;
    bool is_static = false;
};

struct PropertyInfo {
    std::string name;
    std::string type_hint;
    bool readonly = false;
};

struct ConstructorInfo {
    std::vector<ParameterInfo> parameters;
};

struct ClassInfo {
    std::string name;
    std::vector<ConstructorInfo> constructors;
    std::vector<PropertyInfo> properties;
    std::vector<MethodInfo> methods;
};

// Global stub registry (per module)
class StubRegistry {
public:
    static StubRegistry& instance() {
        static StubRegistry registry;
        return registry;
    }

    void add_class(const ClassInfo& info) {
        classes_[info.name] = info;
    }

    ClassInfo& get_or_create_class(const std::string& name) {
        if (classes_.find(name) == classes_.end()) {
            classes_[name] = ClassInfo{name, {}, {}, {}};
        }
        return classes_[name];
    }

    void add_function(const MethodInfo& info) {
        functions_.push_back(info);
    }

    // A bound class is known to the stub by its Python name; type_hint<T>()
    // refers to classes through a typeid placeholder (see type_hint) that
    // generate() resolves against this table, so the hint is right no matter
    // whether the class was bound before or after the method mentioning it.
    void register_type_name(const char* typeid_name, const std::string& py_name) {
        type_names_[typeid_name] = py_name;
    }

    static std::string type_placeholder(const char* typeid_name) {
        return std::string("\x01") + typeid_name + "\x02";
    }

    std::string generate(const std::string& module_name) const {
        return resolve_placeholders(generate_raw(module_name));
    }

    bool write_to_file(const std::string& module_name, const std::string& filename) const {
        std::ofstream file(filename);
        if (!file.is_open()) {
            return false;
        }
        file << generate(module_name);
        return file.good();
    }

    void clear() {
        classes_.clear();
        functions_.clear();
        type_names_.clear();
    }

private:
    StubRegistry() = default;

    std::string generate_raw(const std::string& module_name) const {
        std::ostringstream ss;

        // Module docstring
        ss << "\"\"\"Type stubs for " << module_name << " module.\n\n";
        ss << "Auto-generated by Mirror Bridge stubgen.\n";
        ss << "\"\"\"\n\n";

        // Imports
        ss << "from __future__ import annotations\n";
        ss << "from typing import Any, List, Tuple, Optional, Union, overload\n\n";

        // Classes
        for (const auto& [name, info] : classes_) {
            ss << generate_class_stub(info) << "\n";
        }

        // Module-level functions
        for (const auto& func : functions_) {
            ss << "def " << func.name << "(";
            for (size_t i = 0; i < func.parameters.size(); ++i) {
                if (i > 0) ss << ", ";
                ss << func.parameters[i].name << ": " << func.parameters[i].type_hint;
            }
            ss << ") -> " << func.return_type << ": ...\n";
        }

        return ss.str();
    }

    // Replace every "\x01<typeid name>\x02" with the Python name of that class.
    // Unbound classes keep the old heuristic: their own simple name when it
    // looks like a class, Any otherwise; a template specialization that was
    // never bound has no Python name at all.
    std::string resolve_placeholders(std::string text) const {
        std::string::size_type start = 0;
        while ((start = text.find('\x01', start)) != std::string::npos) {
            auto end = text.find('\x02', start);
            if (end == std::string::npos) break;
            std::string typeid_name = text.substr(start + 1, end - start - 1);
            std::string replacement;
            auto it = type_names_.find(typeid_name);
            if (it != type_names_.end()) {
                replacement = it->second;
            } else {
                replacement = fallback_class_name(typeid_name);
            }
            text.replace(start, end - start + 1, replacement);
            start += replacement.size();
        }
        return text;
    }

    static std::string fallback_class_name(const std::string& typeid_name);

    std::string generate_class_stub(const ClassInfo& info) const {
        std::ostringstream ss;

        ss << "class " << info.name << ":\n";

        // Constructors
        if (info.constructors.empty()) {
            ss << "    def __init__(self) -> None: ...\n";
        } else if (info.constructors.size() == 1) {
            ss << "    def __init__(self";
            for (const auto& param : info.constructors[0].parameters) {
                ss << ", " << param.name << ": " << param.type_hint;
            }
            ss << ") -> None: ...\n";
        } else {
            // Multiple constructors - use @overload
            for (const auto& ctor : info.constructors) {
                ss << "    @overload\n";
                ss << "    def __init__(self";
                for (const auto& param : ctor.parameters) {
                    ss << ", " << param.name << ": " << param.type_hint;
                }
                ss << ") -> None: ...\n";
            }
        }

        // Properties
        for (const auto& prop : info.properties) {
            if (prop.readonly) {
                ss << "    @property\n";
                ss << "    def " << prop.name << "(self) -> " << prop.type_hint << ": ...\n";
            } else {
                ss << "    " << prop.name << ": " << prop.type_hint << "\n";
            }
        }

        // Methods. Overloaded names need @overload or type checkers reject
        // the duplicate definitions.
        std::map<std::string, int> name_counts;
        for (const auto& method : info.methods) {
            ++name_counts[method.name];
        }
        for (const auto& method : info.methods) {
            if (name_counts[method.name] > 1) {
                ss << "    @overload\n";
            }
            if (method.is_static) {
                ss << "    @staticmethod\n";
                ss << "    def " << method.name << "(";
            } else {
                ss << "    def " << method.name << "(self";
                if (!method.parameters.empty()) ss << ", ";
            }

            for (size_t i = 0; i < method.parameters.size(); ++i) {
                if (i > 0) ss << ", ";
                ss << method.parameters[i].name << ": " << method.parameters[i].type_hint;
            }
            ss << ") -> " << method.return_type << ": ...\n";
        }

        // Empty class needs pass
        if (info.constructors.empty() && info.properties.empty() && info.methods.empty()) {
            ss << "    pass\n";
        }

        return ss.str();
    }

    std::map<std::string, ClassInfo> classes_;
    std::vector<MethodInfo> functions_;
    std::map<std::string, std::string> type_names_;
};

// ============================================================================
// Type Hint Helpers
// ============================================================================

// Demangle C++ type names
inline std::string demangle(const char* mangled) {
    int status = 0;
    char* demangled = abi::__cxa_demangle(mangled, nullptr, nullptr, &status);
    if (status == 0 && demangled) {
        std::string result(demangled);
        free(demangled);
        return result;
    }
    return mangled;
}

// Convert C++ type to Python type hint
template<typename T>
std::string type_hint() {
    using CleanT = std::remove_cvref_t<T>;

    // Primitive types
    if constexpr (std::is_same_v<CleanT, bool>) {
        return "bool";
    } else if constexpr (std::is_same_v<CleanT, char>) {
        return "str";
    } else if constexpr (std::is_integral_v<CleanT>) {
        return "int";
    } else if constexpr (std::is_floating_point_v<CleanT>) {
        return "float";
    } else if constexpr (std::is_same_v<CleanT, std::string> ||
                         std::is_same_v<CleanT, std::string_view> ||
                         std::is_same_v<CleanT, const char*>) {
        return "str";
    } else if constexpr (std::is_void_v<CleanT>) {
        return "None";
    }

    // Eigen fixed-size vectors/matrices convert to (nested) Python lists.
    // Detected structurally so this header stays Eigen-independent.
    if constexpr (requires { CleanT::RowsAtCompileTime; CleanT::ColsAtCompileTime;
                             typename CleanT::Scalar; }) {
        std::string scalar =
            std::is_floating_point_v<typename CleanT::Scalar> ? "float" : "int";
        if constexpr (CleanT::ColsAtCompileTime == 1 || CleanT::RowsAtCompileTime == 1) {
            return "list[" + scalar + "]";
        } else {
            return "list[list[" + scalar + "]]";
        }
    }

    // Maps -> dict[K, V] (checked before generic containers: maps iterate too)
    if constexpr (requires { typename CleanT::key_type; typename CleanT::mapped_type; }) {
        return "dict[" + type_hint<typename CleanT::key_type>() + ", " +
               type_hint<typename CleanT::mapped_type>() + "]";
    }

    // Sets -> set[T]
    if constexpr (requires { typename CleanT::key_type; } &&
                  !requires { typename CleanT::mapped_type; }) {
        return "set[" + type_hint<typename CleanT::key_type>() + "]";
    }

    // Byte containers -> bytes
    if constexpr (requires { typename CleanT::value_type; }) {
        using ValueT = typename CleanT::value_type;
        if constexpr (std::is_same_v<ValueT, uint8_t> ||
                      std::is_same_v<ValueT, char> ||
                      std::is_same_v<ValueT, std::byte>) {
            // Check if it's a contiguous container
            if constexpr (requires(CleanT c) { c.data(); c.size(); }) {
                return "bytes";
            }
        }
        // Other containers -> list[T]
        if constexpr (requires { std::declval<CleanT>().begin(); std::declval<CleanT>().end(); }) {
            return "list[" + type_hint<ValueT>() + "]";
        }
    }

    // std::optional -> T | None
    if constexpr (requires { typename CleanT::value_type; std::declval<CleanT>().has_value(); }) {
        return type_hint<typename CleanT::value_type>() + " | None";
    }

    // std::pair/tuple -> tuple[...]
    if constexpr (requires { typename std::tuple_size<CleanT>::type; }) {
        if constexpr (std::tuple_size_v<CleanT> == 2) {
            return "tuple[" + type_hint<std::tuple_element_t<0, CleanT>>() + ", " +
                   type_hint<std::tuple_element_t<1, CleanT>>() + "]";
        }
    }

    // Default: a class. Its Python name is whatever bind_class registered it
    // as (Vec3f for Vector3<float>), which may not be known yet, so leave a
    // placeholder for generate() to resolve.
    return StubRegistry::type_placeholder(typeid(CleanT).name());
}

inline std::string StubRegistry::fallback_class_name(const std::string& typeid_name) {
    std::string name = demangle(typeid_name.c_str());
    if (name.find('<') != std::string::npos) {
        return "Any";
    }
    auto pos = name.rfind("::");
    if (pos != std::string::npos) {
        name = name.substr(pos + 2);
    }
    if (!name.empty() && std::isupper(static_cast<unsigned char>(name[0]))) {
        return name;
    }
    return "Any";
}

// ============================================================================
// Stub Collection During Binding
// ============================================================================

// Called during bind_class to register class metadata
template<typename T>
void register_class_stub(const char* name) {
    ClassInfo& info = StubRegistry::instance().get_or_create_class(name);
    info.name = name;
    StubRegistry::instance().register_type_name(typeid(std::remove_cvref_t<T>).name(), name);
}

// Register a module-level function
template<typename ReturnT, typename... Args>
void register_function_stub(const char* name, const std::vector<std::string>& param_names = {}) {
    MethodInfo func;
    func.name = name;
    func.return_type = type_hint<ReturnT>();

    std::vector<std::string> type_hints = {type_hint<Args>()...};
    for (size_t i = 0; i < type_hints.size(); ++i) {
        std::string pname = (i < param_names.size() && !param_names[i].empty())
                                ? param_names[i]
                                : "arg" + std::to_string(i);
        func.parameters.push_back({pname, type_hints[i]});
    }

    StubRegistry::instance().add_function(func);
}

// Register a property
template<typename T, typename MemberT>
void register_property_stub(const char* class_name, const char* prop_name, bool readonly = false) {
    ClassInfo& info = StubRegistry::instance().get_or_create_class(class_name);
    info.properties.push_back({prop_name, type_hint<MemberT>(), readonly});
}

// Register a method. Parameter names may be empty strings (unnamed params
// in the C++ declaration) — those fall back to argN.
template<typename ReturnT, typename... Args>
void register_method_stub(const char* class_name, const char* method_name,
                          const std::vector<std::string>& param_names = {},
                          bool is_static = false) {
    ClassInfo& info = StubRegistry::instance().get_or_create_class(class_name);

    MethodInfo method;
    method.name = method_name;
    method.return_type = type_hint<ReturnT>();
    method.is_static = is_static;

    // Generate parameters
    std::vector<std::string> type_hints = {type_hint<Args>()...};
    for (size_t i = 0; i < type_hints.size(); ++i) {
        std::string pname = (i < param_names.size() && !param_names[i].empty())
                                ? param_names[i]
                                : "arg" + std::to_string(i);
        method.parameters.push_back({pname, type_hints[i]});
    }

    info.methods.push_back(method);
}

// The runtime always permits zero-arg construction of default-constructible
// classes (py_init's nargs==0 branch), whether or not a default constructor
// was reflected — keep the stub in agreement.
inline void register_default_constructor_if_missing(const char* class_name) {
    ClassInfo& info = StubRegistry::instance().get_or_create_class(class_name);
    for (const auto& ctor : info.constructors) {
        if (ctor.parameters.empty()) return;
    }
    info.constructors.push_back({});
}

// Register a constructor
template<typename... Args>
void register_constructor_stub(const char* class_name,
                               const std::vector<std::string>& param_names = {}) {
    ClassInfo& info = StubRegistry::instance().get_or_create_class(class_name);

    ConstructorInfo ctor;
    std::vector<std::string> type_hints = {type_hint<Args>()...};
    for (size_t i = 0; i < type_hints.size(); ++i) {
        std::string pname = (i < param_names.size() && !param_names[i].empty())
                                ? param_names[i]
                                : "arg" + std::to_string(i);
        ctor.parameters.push_back({pname, type_hints[i]});
    }

    info.constructors.push_back(ctor);
}

// ============================================================================
// Public API
// ============================================================================

// Write stubs to file
inline bool write_stubs(const char* module_name, const char* filename) {
    return StubRegistry::instance().write_to_file(module_name, filename);
}

// Get stub content as string
inline std::string generate_stubs(const char* module_name) {
    return StubRegistry::instance().generate(module_name);
}

// Clear registry (useful for testing)
inline void clear_registry() {
    StubRegistry::instance().clear();
}

} // namespace stubgen
} // namespace mirror_bridge
